main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name="main"

urlpatterns = [
    path('', views.index, name="index"),
	path('login/', views.login_request, name="login"),
    path('logout/', views.logout_request, name="logout"),
    path('register/', views.register, name="register"),
	path('<a_slug>/upload_photo/', views.upload_photo, name="upload_photo"),
    path('add_new/', views.add_new, name="add_new"),
    path('delete_obj/<int:pk>/<int:c_album>/<int:level>/', views.delete_obj, name="delete_obj"),
	path('<single_slug>', views.single_slug, name="single_slug"),
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include("main.urls")),
	path('tinymce/', include('tinymce.urls'))
]

main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from uuid import uuid4
import os

# Create your models here.

class category(models.Model):
	title = models.CharField(max_length=200)
	slug = models.CharField(max_length=200)
	user = models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT)

	class Meta:
		verbose_name_plural = "Categories"
	
	def __str__(self):
		return self.title
		
class album(models.Model):
	title = models.CharField(max_length=200)
	published = models.DateTimeField("date published", default=datetime.now())
	summary = models.CharField(max_length=200)
	
	slug = models.CharField(max_length=200)
	user = models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT)
	class Meta:
		verbose_name_plural = "Albums"
	
	def __str__(self):
		return self.title
	
	def delete(self, *args, **kwargs):
		super().delete(*args, **kwargs)

def content_file_name(instance, filename):
	
	return '/'.join(['images', instance.user.username, filename])

class photo(models.Model):
	filename = models.CharField(max_length=100, default= uuid4().hex + '.jpg')
	published = models.DateTimeField("date published", default=datetime.now())
	user = models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT)
	content = models.FileField(upload_to=content_file_name)
	albums = models.ForeignKey(album, default=1, on_delete=models.SET_DEFAULT)

	def delete(self, *args, **kwargs):
		self.content.delete()
		super().delete(*args, **kwargs)


main/forms.py
from django import forms
from .models import photo, album
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.contrib.auth.models import User
from multiupload.fields import MultiFileField
from uuid import uuid4

def rename(filename):
	filename = replace_space(filename)
	ext = filename.split('.')[-1]
	original = filename.split('.')[0]
	filename = '{}_{}.{}'.format(original, uuid4().hex, ext)
	return filename

def replace_space(somewords):
    return str(somewords).replace(" ","-",-1)

class photoform(forms.ModelForm):
	
	attachments = MultiFileField(min_num=1, max_num=10, max_file_size=2048*2048*10)

	def __init__(self, *args, **kwargs):
		self.c_album = kwargs.pop('instance', None)
		self.c_user = kwargs.pop('c_user', None)
		super().__init__(*args, **kwargs)

	class Meta:
		model = photo
		fields = ('published','attachments')
	
	def save(self):
		for each in self.cleaned_data['attachments']:
			each.name = rename(each.name)
			new_photo = photo(content=each, albums = self.c_album, user = self.c_user)
			new_photo.filename = each.name
			new_photo.save()


class albumform(forms.ModelForm):
	
	def __init__(self, *args, **kwargs):
		self.c_user = kwargs.pop('instance', None)
		super().__init__(*args, **kwargs)

	class Meta:
		model = album
		fields = ('title','published','summary')

	def save(self, commit=True):
		album_save=super(albumform, self).save(commit=False)
		album_save.slug = str(self.cleaned_data['title']).replace(" ","-",-1)
		album_save.user = self.c_user
		if commit:
			album_save.save()
		return album_save

class Newuserform(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(Newuserform, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.files.storage import FileSystemStorage
from .models import category, photo, album
from django.http import HttpResponse
from .forms import photoform, Newuserform, albumform
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.sessions.models import Session
from .apitest import *

# Create your views here.

bucket_prefix = 'hannibal-album-'
localfolder_prefix = 'C:/Users/syringalin/Desktop/django_project/mysite/media/images/'

def index(request):
	if request.user:
		matching_album=album.objects.filter(user__username=request.user.username).order_by('published')
		fst_photo = []
		for a in matching_album:
			if photo.objects.filter(albums__slug=a.slug):
				fst_photo.append(photo.objects.filter(albums__slug=a.slug).earliest("published").content.url) 
			else:
				fst_photo.append('/media/images/album_cover_default.jpg')
		collect = zip(matching_album,fst_photo)
		return render(request,
					template_name="main/albums.html",
					context={"collect":collect})
	else:
		return render(request,
					  template_name="main/albums.html")

def register(request):
	if request.method=="POST":
		form = Newuserform(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f"New Account Created: {username}")
			new_bucket('hannibal-album-' + username)
			login(request, user)
			messages.info(request, f"You are now logged in as {username}")
			return redirect("main:index")
		else:
			for msg in form.error_messages:
				messages.error(request, f"{msg}:{form.error_messages[msg]}")
	form = Newuserform
	return render(request,"main/register.html",{"form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "Logged out successfully! Redirect to Homepage.")
	return redirect("main:index")

def login_request(request):
	if request.method=="POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				current_user=request.user.username
				bucket_check(current_user)
				request.session['cur_user']=current_user
				messages.info(request,f'You are now logged in as {username}')
				return redirect("main:index")
			else:
				messages.error(request, "Invalid username or password")
		else:
			messages.error(request, "Invalid username or password")
	form = AuthenticationForm()
	return render(request,"main/login.html",{"form":form})
	
def upload_photo(request, a_slug):
	pk = get_object_or_404(album, slug=a_slug).pk
	current_user = request.user
	current_album = get_object_or_404(album.objects, pk=pk)
	if request.method == 'POST':
		form = photoform(request.POST, request.FILES, instance=current_album, c_user = current_user)
		if form.is_valid():
			form.save()
			upload_blob(bucket_prefix + current_user.username, current_album.title, localfolder_prefix + current_user.username + '/')
			return redirect('main:single_slug',current_album.slug)
	else:
		form = photoform(instance=current_album, c_user = current_user)
	return render(request, 'main/upload_photo.html', {'form':form,'c_album':current_album})

def add_new(request):
	current_user = request.user
	print(current_user.username)
	if request.method=='POST':
		form = albumform(request.POST, instance=current_user)
		if form.is_valid():
			form.save()
			return redirect("main:index")
	else:
		form = albumform(instance=current_user)
	return render(request, "main/add_new.html", {"form":form})

def single_slug(request, single_slug):
	albums = [ab.slug for ab in album.objects.all()]
	if single_slug in albums:
		matching_photos = photo.objects.filter(albums__slug=single_slug).order_by("published")
		filenames = [str(mp.content.url).split('/')[-1] for mp in matching_photos]
		album_idx = album.objects.only('id').get(slug=single_slug).id
		request.session['album_idx'] = album_idx
		return render(request,
					  'main/photos.html',
					  context={"photos":matching_photos,"c_album":album_idx, "a_slug":single_slug, "c_user":request.user.username, "fn":filenames})
	return HttpResponse(f"{single_slug} is not corresond to anything.")

def delete_obj(request, pk, c_album, level):
	if request.method=="POST":
		current_album = get_object_or_404(album.objects, pk=c_album)
		if level==1:
			current_album.delete()
			return redirect("main:index")
		elif level==2:
			photos = photo.objects.get(pk=pk)
			url = str(photos.content.url)
			filename = url.split('/')[-1]
			d_filelist = []
			d_filelist.append(filename)
		
			delete_blob(request.user.username, current_album.title, d_filelist)
			photos.delete()
			return redirect('main:single_slug', single_slug = current_album.slug)

def bucket_check(current_user):
	client = storage.Client()
	if not client.get_bucket(bucket_prefix + current_user):
		new_bucket(bucket_prefix + current_user)

main/templates/main/add_new.html
{% extends 'main/index.html' %}

{% block content %}
<h2>Create new album</h2>
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Create</button>
</form>

<script>
        document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.fixed-action-btn');
        var instances = M.FloatingActionButton.init(elems, {
            direction: 'left',
            hoverEnabled: false
            });
            });
    
    </script>
    
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large red btn-link" href="/">
            <i class="large material-icons">keyboard_backspace</i>
        </a>
    </div>

{% endblock %}

main/templates/main/albums.html
{% extends 'main/index.html' %}

{% block content %}
<br>
<br>
{% if user.is_authenticated %}
	<div class="row">
		{% for ab, cd in collect %}
		<div class="col s12 m8 l6">	
			<div class="card sticky-action" style="overflow: visible">
				<div class="card-image waves-effect waves-block waves-light">
					<img class="activator" src="{{ cd }}">
				</div>
				<div class="card-content">
					<span class="card-title" style="color:darkslategrey">{{ ab.title }}</span>
				</div>
				<div class="card-action">
					<a href="{{ ab.slug }}">Explore</a>
				</div>
				<div class="card-reveal" style="display: none; transform: translateY(100%)">
					<span class="card-title grey-test test-darken-4">
						{{ ab.title }}
						<i class="material_icons right">close</i>
						<form method="POST" action="{% url 'main:delete_obj' ab.pk ab.pk 1 %}">
							{% csrf_token %}
							<button type="submit" class="btn">Delete</button>
						</form>
					</span>
					<p>
						{{ ab.summary }}
					</p>
				</div>
			</div>
		</div>
		{% endfor %}
		
		<div class="col s12 m8 l6">
			<div class="card">
				<a class="btn-link" href="add_new/">
					<div class="center">
						<p class="card-content" style="font-stretch: expanded; font-size:xx-large">Add new album</p>
					</div>
				</a>
			</div>
		</div>

		<script>
			document.addEventListener('DOMContentLoaded', function() {
			var elems = document.querySelectorAll('.fixed-action-btn');
			var instances = M.FloatingActionButton.init(elems, {
				direction: 'left',
				hoverEnabled: false
				});
				});
		
		</script>
		
		<div class="fixed-action-btn">
			<a class="btn-floating btn-large red">
				<i class="large material-icons">menu</i>
			</a>
			<ul>
				<li><a class="btn-floating yellow darken-2" href="#top"><i class="material-icons">keyboard_arrow_up</i></a></li>
				<li><a class="btn-floating blue btn-link" href="add_new/"><i class="material-icons">add</i></a></li>
			</ul>
		</div>
	</div>
{% else %}
    <div class="col s12 m8 l6">
        <div class="card-content">
            <div class="carousel carousel-slider">
                <a class="carousel-item" href="#one!"><img src="https://lorempixel.com/800/400/food/1"></a>
                <a class="carousel-item" href="#two!"><img src="https://lorempixel.com/800/400/food/2"></a>
                <a class="carousel-item" href="#three!"><img src="https://lorempixel.com/800/400/food/3"></a>
                <a class="carousel-item" href="#four!"><img src="https://lorempixel.com/800/400/food/4"></a>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

main/templates/main/index.html
<head>
	{% load static %}
	{% block css %}
		<link href="tinymce/static/tinymce/css/prism.css">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
		<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>
	{% endblock css %}
	
</head>
<body>
	<div id="top" class="section scrollspy">
		{% include "main/includes/navbar.html" %}
		{% include "main/includes/messages.html" %}
	</div>
	<div class="container">
	  <br>
	  {% block content %}
	  {% endblock %}
	</div>

</body>

<script>M.AutoInit();</script>
<script>$('.carousel.carousel-slider').carousel({
	fullWidth: true
});</script>
<script>$(".dropdown-trigger").dropdown({
		coverTrigger: false
		});</script>

main/templates/main/login.html
{% extends 'main/index.html' %}


{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn" style="background-color: darkred; color:floralwhite" type="submit">Login</button>
  </form>
  <p><a href="forgot_password">Forgot password</a></p>
  <p>If you don't already have an account, <a href="/register/"><strong>Register</strong>></a> for one.</p>
{% endblock %}

main/templates/main/photos.html
{% extends 'main/index.html' %}


{% block content %}

<div class="row">
	{% if photos %}
		{% for p in photos %}
			<div class="col s12 m8 l6" style="width:75%">
				<div class="card" >
					<div class="card-image waves-effect">
						<img class="activator" src="https://storage.cloud.google.com/hannibal-album-{{ c_user }}/{{ a_slug }}/{{ p.filename }}" style="text-align: center">
					</div>
					<div class="card-reveal" style="display: none; transform: translateY(100%)">
						<span class="card-title activator grey-test test-darken-4"><i class="material-icons right">close</i>
							<form method="POST" action="{% url 'main:delete_obj' p.pk c_album 2 %}">
								{% csrf_token %}
								<button type="submit" class="btn">Delete</button>
							</form>
						</span>
					</div>
				</div>
			</div>
		{% endfor %}
	{% endif %}
	<div class="col s12 m8 l6" style="width:50%; height:fit-content ">
		<div class="card">
			<a class="btn-link" href="{% url 'main:upload_photo' a_slug %}">
				<div class="card-image waves-effect" center>
					<img class="activator" src="/media/images/album_cover_default.jpg" style="text-align: center">
				</div>
			</a>
		</div>
	</div>
</div>

<script>
	document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.fixed-action-btn');
    var instances = M.FloatingActionButton.init(elems, {
      direction: 'left',
      hoverEnabled: true
 	  });
  	});

</script>

<div class="fixed-action-btn">
	<a class="btn-floating btn-large red">
	  <i class="large material-icons">menu</i>
	</a>
	<ul>
	  <li><a class="btn-floating red btn-link" href="/"><i class="material-icons">keyboard_backspace</i></a></li>
	  <li><a class="btn-floating yellow darken-2" href="#top"><i class="large material-icons">keyboard_arrow_up</i></a></li>
	  <li><a class="btn-floating blue btn-link" href="{% url 'main:upload_photo' a_slug %}"><i class="material-icons">file_upload</i></a></li>
	</ul>
</div>
{% endblock %}

main/templates/main/register.html
{% extends 'main/index.html' %}


{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn" style="background-color: darkred; color:floralwhite" type="submit">Register</button>
  </form>

  If you already have an account, <a href="/login/"><strong>Login</strong></a> here.
{% endblock %}

main/templates/main/upload_photo.html
{% extends 'main/index.html' %}


{% block content %}
    <h2>Upload photo</h2>
    <form method="post" enctype="multipart/form-data" multiple>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
    </form>
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large red btn-link" href="{% url 'main:single_slug' c_album.slug %}">
            <i class="large material-icons">keyboard_backspace</i>
        </a>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.fixed-action-btn');
        var instances = M.FloatingActionButton.init(elems, {
            direction: 'left',
            hoverEnabled: false
            });
            });
    </script>
{% endblock %}